### PR TITLE
v1 release 

### PR DESCRIPTION
**Pull request by pbteja1998**
# What kind of change does this PR introduce

Merge `develop` branch to `master` as requirements of `v1` release are implemented.

### Checklist for this PR
* [x] I have read [contributing guidelines](https://github.com/coderplex/coderplex-backend/blob/develop/.github/CONTRIBUTING.md).
* [N/A] Updated the requirements (`pip freeze > requirements/requirements.txt`). 
* [N/A] Created new migrations (`python webapp/manage.py makemigrations && python webapp/manage.py migrate`).
* [N/A] Pull request is towards `develop` branch.
* [N/A] Documentation
* [x] Ready to be merged.

### CODE REVIEW

**Comment by pbteja1998** [comment]
@rrmerugu Are there any requirements that are left for `v1` release? AFAIK Everything is done. We should merge `develop` branch to `master` and deploy `master` in `aws`. If there are nothing left, merge this pull request and then deploy into `aws`.

**Comment by rrmerugu** [comment]
sounds cool, @pbteja1998  when are you planning to start with the automation tests ?

**Review by rrmerugu — APPROVED** [review]
We need to write automation tests right after this release plan, thats one thing we missed so far.

**Comment by pbteja1998** [comment]
Yes, currently @mohanarunachalam is working on tests. We will discuss the progress of that in the upcoming call.

**Pull request merged**
