### PR TITLE
Added contributing guidelines

### PR DESCRIPTION
**Pull request by pbteja1998**
Added docs similar to those that are present in `Coderplex Frontend repo`.
* [x] Added `Contributing Guidelines`.
* [x] Added `Code Of Conduct`.
* [x] Added `License`.
* [x] Added `Issue Template`.
* [x] Added `Pull Request Template`.
* [x] Added `Fixtures/Seeders` to automatically seed Social Application data to the database.

### CODE REVIEW

**Comment by pbteja1998** [comment]
@rrmerugu anything else you wanna add, or shall I merge this pull request?

**Comment by rrmerugu** [comment]
Great @pbteja1998.. All looks good. but just a suggestion for next time, see  that, you will not send multiple features in a single PR, making PR at feature level is easy to revert back when needed. But this looks good.

**Comment by pbteja1998** [comment]
I though that all are docs, hence sent all those in the same pr. I will change it from next time.

**Comment by rrmerugu** [comment]
Yeah. thats ok. but `removed FieldSerializers in UserProfileEditSerializer` and fixtures doesn't belong to doc feature. so but in the initial stages , this is fine for now, you are fixing what ever you see, which is good. but in near future focus, lets try to send on feature per PR.

**Comment by rrmerugu** [comment]
let me know when can I close this ? also, since you are making API.md changes, did you get chance to look into swagger API documentation ? please look into that, and see which approach works for us.

**Comment by pbteja1998** [comment]
`removed FieldSerializers in UserProfileEditSerializer` is minor change, and it should be changed if anyone has to contribute, and about `fixtures`, I added those in this pr because, in Contributing Guidelines, I added a command to run these fixtures, so that they do not have to manually add social applications. So both these are necessary, if CONTRIBUTING.md is merged, that's why i added those in this pr

**Comment by pbteja1998** [comment]
I saw swagger API documentation , but it is not clear and flexible, so I thought that we could use [this](https://gist.github.com/iros/3426278) to make API documentation more flexible

**Comment by pbteja1998** [comment]
Do you think that Swagger will be better than this, we can have both if we want.

**Comment by rrmerugu** [comment]
https://django-rest-swagger.readthedocs.io/en/latest/ If we use this, a live documentation of the APIs where you can test without any extra code for documentation will be generation.  It lets you create API documentation with just config changes, so we don't have to write this API.md . Anything thats is manual is prone to error. Also,  Swagger as the site says  " is the world’s largest framework of API developer tools for the OpenAPI Specification(OAS), enabling development across the entire API lifecycle, from design and documentation, to test and deployment." .So why not use the best tech in the space. It might throw you off with some new things, but its worth it. With DRF, it works with just config in settings.py. please look into it, we can add that in another PR later

https://hirelofty.com/blog/auto-generate-swagger-docs-your-django-api/

**Comment by pbteja1998** [comment]
Ok sure.... I will look in to that

**Pull request merged**
