### PR TITLE
[requires.io] dependency update on develop branch

### PR DESCRIPTION
**Pull request by pbteja1998**

### CODE REVIEW

**Comment by vinaypuppal** [comment]
@pbteja1998 Can you add `coderplex-bot` as user for `requires.io` PR's instead of your account. I will share `coderplex-bot` credentials in discord with you.

**Comment by pbteja1998** [comment]
@vinaypuppal ok Sure...

**Comment by pbteja1998** [comment]
[Release 2.0 Release Notes](https://docs.djangoproject.com/en/2.0/releases/2.0/)
@rrmerugu The above are the release notes for `Django 2.0` . Do you think we should upgrade to `2.0` or stay in `1.11.7`

**Comment by pbteja1998** [comment]
It seems like build has failed with the existing code if we use `Django 2.0`

**Comment by rrmerugu** [comment]
First of all 1.11 is the LTS so we can bet on it for support and updates. 

while I understand the concept of using the latest tech in space. but generally it takes a while for all the supporting app around the Django to support the latest 2.0. So its ideal to stick with LTS (Django 1.11 in this case) to avoid any such support issues.

```
Django 2.0 will be the last release series to support Python 3.4. If you plan a deployment of Python 3.4 beyond the end-of-life for Django 2.0 (April 2019), stick with Django 1.11 LTS (supported until April 
2020) instead. Note, however, that the end-of-life for Python 3.4 is March 2019.

Reference: https://docs.djangoproject.com/en/2.0/releases/2.0/#python-compatibility
```

This is one of the reasons why we use 3.6 as well..

**Comment by pbteja1998** [comment]
Yeah, you are right...

**Comment by pbteja1998** [comment]
@rrmerugu  I added `rq filter` to `django` in `requirements.txt`. Basically what it does is, if any new django version greater than the present version and less than `2.0` is found, then `requires.io` notifies with pull request, otherwise it still shows that the requirements are up to date.

Source: https://requires.io/features/

**Comment by pbteja1998** [comment]
You can approve and merge this now.

**Comment by rrmerugu** [comment]
sounds good, but we don't need to support multiple version of Django, this project is not a library, which would be used as a part of another application, since this is a standalone application that can run on its own and destined to run on a single environment, we can stick with one version.

**Comment by pbteja1998** [comment]
Ok, then I will add filter to be equal to `1.11.7`, otherwise the `requires.io` badge will show outdated even though all the requirements are up to date.

**Review by rrmerugu — DISMISSED** [review]

**Review by rrmerugu — APPROVED** [review]

**Pull request merged**
