### PR TITLE
[requires.io] dependency update on develop branch

### PR DESCRIPTION
**Pull request by pbteja1998**

### CODE REVIEW

**Review by rrmerugu — APPROVED** [review]

**Comment by rrmerugu** [comment]
This looks cool, should we keep `requires-io-devel` branch ? or can we delete it @pbteja1998

**Comment by M-ZubairAhmed** [comment]
@rrmerugu we usually delete branches from pr as they get adding up.

**Comment by rrmerugu** [comment]
Yeah @M-ZubairAhmed, thats why trying to confirm the same with @pbteja1998

**Comment by pbteja1998** [comment]
Yes, everytime a dependency update comes, `requires.io` opens pull request with my account by creating a new branch. So no problem even if we delete the `requires-io-develop` branch

**Pull request merged**
